spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fimapi-db
    username: postgres
    password: ${DB_PASSWORD:motdepasse}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  
  sql:
    init:
      mode: always
